version: 2

jobs:
  compare_test:
    docker:
      - image: circleci/ruby:2.4.4-stretch-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: bundle install
      - run: bundle exec rake test:unit
  automation_test:
    docker:
      - image: circleci/ruby:2.4.4-stretch-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: bundle install
      - run: bundle exec rake test:integration

workflows:
  version: 2
  test:
    jobs:
      - compare_test
      - automation_test

